### ISSUE TITLE
Core Feature: Sign-in/Sign-up Page

### ISSUE THREAD

**Issue by nihagaddam** [info442-spr22/g-team#1]
List out requirements for Sign-in/Sign-up Page.

**Comment by fretws** [comment]
Implement the 'Log In' page in the [Figma document]().

Behavior
- [ ] Form validation for the email to be in valid email format
- [ ] Print form input as a JS object to the console, until we implement a back end for authentication
- [ ] When the Log In button is clicked, it is disabled and a loading icon is displayed inside of the button while the information is being submitted (it's ok if this only changes the URL if we do not yet have a home page)
- [ ] The 'create account' link should direct the user to the 'create account' page
- [ ] Update the 'create account' page so that the 'log in' link directs to the log in page
