### ISSUE TITLE
Minor Bug: When making screen smaller you cannot move to tool/scroll 

### ISSUE THREAD

**Issue by abequette99** [info442-spr22/g-team#148]
Summary: When making the screen smaller I am unable to move about the page anymore or access any of the tools to make a drawing. Overall, it is like the webpage is frozen in the top left quadrant of the application. 

Environment: Chrome Version 101.0.4951.67 

Steps: 1. grab top bar of website and drag down to pull it out of full screen then it gets stuck.

Expected results: Canvas would get smaller and I would be able to access tools and save note book

Actual results: I am stuck in the upper left quadrant of application

**Comment by cherimarie** [comment]
This is not a good user experience, but for our purposes, it's a "minor" bug. The tool is still usable on larger screens.

**Comment by cavazd** [comment]
Make canvas scalable and adjust to screen size changing

**Comment by sharlenef** [comment]
This bug will be fixed in the next iteration so that users can make their screens smaller and still properly view the site. In addition, our canvas isn't scoped to be usable on a smaller screen. So we will add in media queries and let users know that their screen size isn't compatible if they're using a smaller screen.
